function template(locals) {
var jade_debug = [ new jade.DebugItem( 1, "index.jade" ) ];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;

jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 2, "index.jade" ));
buf.push("<html>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 3, "index.jade" ));
buf.push("<head>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 4, "index.jade" ));
buf.push("<title>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 4, jade_debug[0].filename ));
buf.push("Guia Turistica Mexico");
jade_debug.shift();
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 6, "index.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"css/normalize.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 7, "index.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"css/style.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 8, "index.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"css/font-style.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 9, "index.jade" ));
buf.push("<link rel=\"import\" href=\"polymer-elements/header.html\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 10, "index.jade" ));
buf.push("<link rel=\"import\" href=\"polymer-elements/estados.html\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 11, "index.jade" ));
buf.push("<link rel=\"import\" href=\"polymer-elements/arte-cultura.html\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 12, "index.jade" ));
buf.push("<link rel=\"import\" href=\"polymer-elements/header-min.html\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 13, "index.jade" ));
buf.push("<script src=\"scripts/grid.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 14, "index.jade" ));
buf.push("<script src=\"bower_components/webcomponentsjs/webcomponents-lite.min.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 15, "index.jade" ));
buf.push("<meta charset=\"utf-8\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 16, "index.jade" ));
buf.push("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</head>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 18, "index.jade" ));
buf.push("<body>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 19, "index.jade" ));
buf.push("<header-min-polymer>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</header-min-polymer>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 20, "index.jade" ));
buf.push("<header-polymer>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</header-polymer>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 21, "index.jade" ));
buf.push("<estados-polymer>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</estados-polymer>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 22, "index.jade" ));
buf.push("<ac-polymer>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</ac-polymer>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 24, "index.jade" ));
buf.push("<section class=\"info-section\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 25, "index.jade" ));
buf.push("<section class=\"principal-image\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 26, "index.jade" ));
buf.push("<img src=\"img/Header-image1.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 27, "index.jade" ));
buf.push("<span class=\"header-image-name\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push("Chichén Itzá");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 28, "index.jade" ));
buf.push("<span>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 28, jade_debug[0].filename ));
buf.push("Yucatán");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 30, "index.jade" ));
buf.push("<section class=\"videos-youtube\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 33, "index.jade" ));
buf.push("<iframe width=\"80%\" height=\"100%\" src=\"https://www.youtube.com/embed/e8XMVYkcjQA\" class=\"videos-index\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</iframe>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 35, "index.jade" ));
buf.push("<iframe width=\"80%\" height=\"100%\" src=\"https://www.youtube.com/embed/BVmiUuOmixo\" class=\"videos-index\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</iframe>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 37, "index.jade" ));
buf.push("<iframe width=\"80%\" height=\"100%\" src=\"https://www.youtube.com/embed/pU-vyVKlUDs\" class=\"videos-index\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</iframe>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 39, "index.jade" ));
buf.push("<iframe width=\"80%\" height=\"100%\" src=\"https://www.youtube.com/embed/Yo55Qs6mHuU\" class=\"videos-index\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</iframe>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 41, "index.jade" ));
buf.push("<iframe width=\"80%\" height=\"100%\" src=\"https://www.youtube.com/embed/oCKywHaziB0\" class=\"videos-index\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</iframe>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 43, "index.jade" ));
buf.push("<iframe width=\"80%\" height=\"100%\" src=\"https://www.youtube.com/embed/8Uq5wLCIvhc\" class=\"videos-index\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</iframe>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 45, "index.jade" ));
buf.push("<iframe width=\"80%\" height=\"100%\" src=\"https://www.youtube.com/embed/fa6-5Qo4TIU\" class=\"videos-index\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</iframe>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, "index.jade" ));
buf.push("<iframe width=\"80%\" height=\"100%\" src=\"https://www.youtube.com/embed/GfKWAWM4bcI\" class=\"videos-index\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</iframe>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 50, "index.jade" ));
buf.push("<div class=\"informacion\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 51, "index.jade" ));
buf.push("<section id=\"grid_container\" class=\"info-section-elements\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 52, "index.jade" ));
buf.push("<section class=\"info-section-element\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 53, "index.jade" ));
buf.push("<h4>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 54, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 54, jade_debug[0].filename ));
buf.push("Manuel Felgueréz");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 55, "index.jade" ));
buf.push("<img src=\"img/GT-1.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 56, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 56, jade_debug[0].filename ));
buf.push("Manuel Felguérez nació el 12 de Diciembre de 1928 en el seno de una familia aristocrática. Fue hijo primogénito de un terrateniente de Zacatecas.");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 57, "index.jade" ));
buf.push("<a href=\"\" class=\"ver-más-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 57, jade_debug[0].filename ));
buf.push(" Personajes...");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 58, "index.jade" ));
buf.push("<section class=\"info-section-element\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 59, "index.jade" ));
buf.push("<h4>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 60, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 60, jade_debug[0].filename ));
buf.push("Feria del Globo");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 61, "index.jade" ));
buf.push("<img src=\"img/GT-2.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 62, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 62, jade_debug[0].filename ));
buf.push("En este bello lugar se le da una connotación muy especial a la fiesta de difuntos: la elevación de globos y faroles de papel de china. ");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 63, "index.jade" ));
buf.push("<a href=\"\" class=\"ver-más-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 63, jade_debug[0].filename ));
buf.push(" Festivales...");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 65, "index.jade" ));
buf.push("<section class=\"info-section-element\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 66, "index.jade" ));
buf.push("<h4>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 67, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 67, jade_debug[0].filename ));
buf.push("Cuajilote");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 68, "index.jade" ));
buf.push("<img src=\"img/GT-3.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 69, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 69, jade_debug[0].filename ));
buf.push("Esta región fue receptora y redistribuidora comercial, aprovechando la red de comunicaciones demarcada por la fisiografía. ");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 70, "index.jade" ));
buf.push("<a href=\"\" class=\"ver-más-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 70, jade_debug[0].filename ));
buf.push(" Zonas Arqueológicas..");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 72, "index.jade" ));
buf.push("<section class=\"info-section-element\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 73, "index.jade" ));
buf.push("<h4>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 74, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 74, jade_debug[0].filename ));
buf.push("Marimba chiapaneca");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 75, "index.jade" ));
buf.push("<img src=\"img/GT-4.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 76, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 76, jade_debug[0].filename ));
buf.push("La marimba tradicional mexicana proviene de Tabasco, Chiapas y Guatemala, y tiene su origen en instrumentos que introdujeron los esclavos negros en la época de la conquista.");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 77, "index.jade" ));
buf.push("<a href=\"\" class=\"ver-más-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 77, jade_debug[0].filename ));
buf.push(" Cultura Nacional...");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 78, "index.jade" ));
buf.push("<section class=\"info-section-element\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 79, "index.jade" ));
buf.push("<h4>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 80, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 80, jade_debug[0].filename ));
buf.push("Barrancas del Cobre");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 81, "index.jade" ));
buf.push("<img src=\"img/GT-5.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 82, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 82, jade_debug[0].filename ));
buf.push("Sobre una extensión de 600 km de longitud y 250 km de anchura se extienden las majestuosas Barrancas del Cobre, parque natural ubicado dentro del estado de Chihuahua.");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 83, "index.jade" ));
buf.push("<a href=\"\" class=\"ver-más-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 83, jade_debug[0].filename ));
buf.push(" Destinos...");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 85, "index.jade" ));
buf.push("<section class=\"info-section-element\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 86, "index.jade" ));
buf.push("<h4>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 87, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 87, jade_debug[0].filename ));
buf.push("Isla Mujeres");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 88, "index.jade" ));
buf.push("<img src=\"img/GT-6.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 89, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 89, jade_debug[0].filename ));
buf.push("Las primeras noticias de Isla Mujeres datan del periodo comprendido entre el 564 y el 1516 dC, y la ubican como una provincia maya de Ekab.");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 90, "index.jade" ));
buf.push("<a href=\"\" class=\"ver-más-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 90, jade_debug[0].filename ));
buf.push(" Destinos..");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 92, "index.jade" ));
buf.push("<section class=\"info-section-element\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 93, "index.jade" ));
buf.push("<h4>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 94, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 94, jade_debug[0].filename ));
buf.push("Ixtapa Zihuatanejo");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 95, "index.jade" ));
buf.push("<img src=\"img/GT-7.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 96, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 96, jade_debug[0].filename ));
buf.push("La palabra Zihuatanejo, una tiene origen en los vocablos en purépechas itzi: agua, huata: cerro y nejo: amarillo verdoso, que en conjunto se expresa como \"Agua del cerro amarillo\".");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 97, "index.jade" ));
buf.push("<a href=\"\" class=\"ver-más-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 97, jade_debug[0].filename ));
buf.push(" Destinos...");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 99, "index.jade" ));
buf.push("<section class=\"info-section-element\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 100, "index.jade" ));
buf.push("<h4>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 101, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 101, jade_debug[0].filename ));
buf.push("La casa de los azulejos");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 102, "index.jade" ));
buf.push("<img src=\"img/GT-8.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 103, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 103, jade_debug[0].filename ));
buf.push("La Casa de los Azulejos es un palacio ubicado en el centro histórico de la Ciudad de México (entre las Calle Francisco I. Madero y la Calle Cinco de Mayo).");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 104, "index.jade" ));
buf.push("<a href=\"\" class=\"ver-más-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 104, jade_debug[0].filename ));
buf.push(" Cultura Nacional...");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 106, "index.jade" ));
buf.push("<section class=\"info-section-element\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 107, "index.jade" ));
buf.push("<h4>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 108, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 108, jade_debug[0].filename ));
buf.push("Tajín");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 109, "index.jade" ));
buf.push("<img src=\"img/GT-9.jpg\" alt=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 110, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 110, jade_debug[0].filename ));
buf.push("La antigua ciudad de El Tajín se desarrolló a fines del horizonte Clásico, y llegó a su apogeo en la transición al Posclásico, o sea entre 800 y 1150.");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 111, "index.jade" ));
buf.push("<a href=\"\" class=\"ver-más-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 111, jade_debug[0].filename ));
buf.push(" Zonas Arqueológicas...");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 115, "index.jade" ));
buf.push("<img src=\"img/banner-publi.jpg\" alt=\"\" class=\"banner-abajo\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 116, "index.jade" ));
buf.push("<footer>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 117, "index.jade" ));
buf.push("<ul>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 118, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 119, "index.jade" ));
buf.push("<a href=\"https://www.youtube.com/watch?v=6RuDx0RKjok\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 119, jade_debug[0].filename ));
buf.push("¿Qué es la Guía Turística México?");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 120, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 121, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 121, jade_debug[0].filename ));
buf.push("Contacto");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 122, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 123, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 123, jade_debug[0].filename ));
buf.push("Términos de Uso");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 124, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 125, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 125, jade_debug[0].filename ));
buf.push("Políticas de privacidad");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 126, "index.jade" ));
buf.push("<div class=\"parrafo-footer\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 127, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 127, jade_debug[0].filename ));
buf.push("Copyright Guía Turística México © 2015. Todos los derechos reservados. Prohibida la reproducción parcial o total sin previa autorización expresa y por escrito de Directorios y Guías VB SA de CV. Génova 20-5, colonia Juárez, C.P. 06600, México D.F.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 128, "index.jade" ));
buf.push("<span>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 128, jade_debug[0].filename ));
buf.push("Desarrollado por ");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 129, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 129, jade_debug[0].filename ));
buf.push("Meinen.mx");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</footer>");
jade_debug.shift();
jade_debug.shift();
buf.push("</body>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 131, "index.jade" ));
buf.push("<script src=\"scripts/jquery.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 132, "index.jade" ));
buf.push("<script src=\"../scripts/jquery.cookie.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 133, "index.jade" ));
buf.push("<script src=\"scripts/jquery-changes.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("</html>");
jade_debug.shift();
jade_debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "doctype html\nhtml\n\thead\n\t\ttitle Guia Turistica Mexico\n\n\t\tlink(rel=\"stylesheet\", href=\"css/normalize.css\")\n\t\tlink(rel=\"stylesheet\", href=\"css/style.css\")\n\t\tlink(rel=\"stylesheet\", href=\"css/font-style.css\")\n\t\tlink(rel=\"import\", href=\"polymer-elements/header.html\")\n\t\tlink(rel=\"import\", href=\"polymer-elements/estados.html\")\n\t\tlink(rel=\"import\", href=\"polymer-elements/arte-cultura.html\")\n\t\tlink(rel=\"import\", href=\"polymer-elements/header-min.html\")\n\t\tscript(src=\"scripts/grid.js\")\n\t\tscript(src=\"bower_components/webcomponentsjs/webcomponents-lite.min.js\")\n\t\tmeta(charset=\"utf-8\")\n\t\tmeta(name=\"viewport\", content=\"width=device-width, initial-scale=1.0\")\n\n\tbody\n\t\theader-min-polymer\n\t\theader-polymer\n\t\testados-polymer\n\t\tac-polymer\n\n\t\tsection(class=\"info-section\")\n\t\t\tsection(class=\"principal-image\")\n\t\t\t\t\timg(src=\"img/Header-image1.jpg\", alt=\"\")\n\t\t\t\t\tspan(class=\"header-image-name\") Chichén Itzá\n\t\t\t\t\t\tspan Yucatán\n\n\t\t\tsection(class=\"videos-youtube\")\n\n\n\t\t\t\tiframe(class=\"videos-index\" width=\"80%\", height=\"100%\", src=\"https://www.youtube.com/embed/e8XMVYkcjQA\")\n\n\t\t\t\tiframe(class=\"videos-index\" width=\"80%\", height=\"100%\", src=\"https://www.youtube.com/embed/BVmiUuOmixo\")\n\n\t\t\t\tiframe(class=\"videos-index\" width=\"80%\", height=\"100%\", src=\"https://www.youtube.com/embed/pU-vyVKlUDs\")\n\n\t\t\t\tiframe(class=\"videos-index\" width=\"80%\", height=\"100%\", src=\"https://www.youtube.com/embed/Yo55Qs6mHuU\")\n\n\t\t\t\tiframe(class=\"videos-index\" width=\"80%\", height=\"100%\", src=\"https://www.youtube.com/embed/oCKywHaziB0\")\n\n\t\t\t\tiframe(class=\"videos-index\" width=\"80%\", height=\"100%\", src=\"https://www.youtube.com/embed/8Uq5wLCIvhc\")\n\n\t\t\t\tiframe(class=\"videos-index\" width=\"80%\", height=\"100%\", src=\"https://www.youtube.com/embed/fa6-5Qo4TIU\")\n\n\t\t\t\tiframe(class=\"videos-index\" width=\"80%\", height=\"100%\", src=\"https://www.youtube.com/embed/GfKWAWM4bcI\")\n\n\n\t\t\tdiv.informacion\n\t\t\t\tsection(class=\"info-section-elements\", id=\"grid_container\")\n\t\t\t\t\tsection(class=\"info-section-element\")\n\t\t\t\t\t\th4\n\t\t\t\t\t\t\ta(href=\"\") Manuel Felgueréz\n\t\t\t\t\t\timg(src=\"img/GT-1.jpg\", alt=\"\")\n\t\t\t\t\t\tp Manuel Felguérez nació el 12 de Diciembre de 1928 en el seno de una familia aristocrática. Fue hijo primogénito de un terrateniente de Zacatecas.\n\t\t\t\t\t\t\ta(href=\"\", class=\"ver-más-link\")  Personajes...\n\t\t\t\t\tsection(class=\"info-section-element\")\n\t\t\t\t\t\th4\n\t\t\t\t\t\t\ta(href=\"\") Feria del Globo\n\t\t\t\t\t\timg(src=\"img/GT-2.jpg\", alt=\"\")\n\t\t\t\t\t\tp En este bello lugar se le da una connotación muy especial a la fiesta de difuntos: la elevación de globos y faroles de papel de china. \n\t\t\t\t\t\t\ta(href=\"\", class=\"ver-más-link\")  Festivales...\n\n\t\t\t\t\tsection(class=\"info-section-element\")\n\t\t\t\t\t\th4\n\t\t\t\t\t\t\ta(href=\"\") Cuajilote\n\t\t\t\t\t\timg(src=\"img/GT-3.jpg\", alt=\"\")\n\t\t\t\t\t\tp Esta región fue receptora y redistribuidora comercial, aprovechando la red de comunicaciones demarcada por la fisiografía. \n\t\t\t\t\t\t\ta(href=\"\", class=\"ver-más-link\")  Zonas Arqueológicas..\n\n\t\t\t\t\tsection(class=\"info-section-element\")\n\t\t\t\t\t\th4\n\t\t\t\t\t\t\ta(href=\"\") Marimba chiapaneca\n\t\t\t\t\t\timg(src=\"img/GT-4.jpg\", alt=\"\")\n\t\t\t\t\t\tp La marimba tradicional mexicana proviene de Tabasco, Chiapas y Guatemala, y tiene su origen en instrumentos que introdujeron los esclavos negros en la época de la conquista.\n\t\t\t\t\t\t\ta(href=\"\", class=\"ver-más-link\")  Cultura Nacional...\n\t\t\t\t\tsection(class=\"info-section-element\")\n\t\t\t\t\t\th4\n\t\t\t\t\t\t\ta(href=\"\") Barrancas del Cobre\n\t\t\t\t\t\timg(src=\"img/GT-5.jpg\", alt=\"\")\n\t\t\t\t\t\tp Sobre una extensión de 600 km de longitud y 250 km de anchura se extienden las majestuosas Barrancas del Cobre, parque natural ubicado dentro del estado de Chihuahua.\n\t\t\t\t\t\t\ta(href=\"\", class=\"ver-más-link\")  Destinos...\n\t\t\t\t\t\n\t\t\t\t\tsection(class=\"info-section-element\")\n\t\t\t\t\t\th4\n\t\t\t\t\t\t\ta(href=\"\") Isla Mujeres\n\t\t\t\t\t\timg(src=\"img/GT-6.jpg\", alt=\"\")\n\t\t\t\t\t\tp Las primeras noticias de Isla Mujeres datan del periodo comprendido entre el 564 y el 1516 dC, y la ubican como una provincia maya de Ekab.\n\t\t\t\t\t\t\ta(href=\"\", class=\"ver-más-link\")  Destinos..\n\n\t\t\t\t\tsection(class=\"info-section-element\")\n\t\t\t\t\t\th4\n\t\t\t\t\t\t\ta(href=\"\") Ixtapa Zihuatanejo\n\t\t\t\t\t\timg(src=\"img/GT-7.jpg\", alt=\"\")\n\t\t\t\t\t\tp La palabra Zihuatanejo, una tiene origen en los vocablos en purépechas itzi: agua, huata: cerro y nejo: amarillo verdoso, que en conjunto se expresa como \"Agua del cerro amarillo\".\n\t\t\t\t\t\t\ta(href=\"\", class=\"ver-más-link\")  Destinos...\n\n\t\t\t\t\tsection(class=\"info-section-element\")\n\t\t\t\t\t\th4\n\t\t\t\t\t\t\ta(href=\"\") La casa de los azulejos\n\t\t\t\t\t\timg(src=\"img/GT-8.jpg\", alt=\"\")\n\t\t\t\t\t\tp La Casa de los Azulejos es un palacio ubicado en el centro histórico de la Ciudad de México (entre las Calle Francisco I. Madero y la Calle Cinco de Mayo).\n\t\t\t\t\t\t\ta(href=\"\", class=\"ver-más-link\")  Cultura Nacional...\n\n\t\t\t\t\tsection(class=\"info-section-element\")\n\t\t\t\t\t\th4\n\t\t\t\t\t\t\ta(href=\"\") Tajín\n\t\t\t\t\t\timg(src=\"img/GT-9.jpg\", alt=\"\")\n\t\t\t\t\t\tp La antigua ciudad de El Tajín se desarrolló a fines del horizonte Clásico, y llegó a su apogeo en la transición al Posclásico, o sea entre 800 y 1150.\n\t\t\t\t\t\t\ta(href=\"\", class=\"ver-más-link\")  Zonas Arqueológicas...\n\n\t\t\n\t\t\t\n\t\t\timg(src=\"img/banner-publi.jpg\", alt=\"\", class=\"banner-abajo\")\n\t\tfooter\n\t\t\tul\n\t\t\t\tli\n\t\t\t\t\ta(href=\"https://www.youtube.com/watch?v=6RuDx0RKjok\") ¿Qué es la Guía Turística México?\n\t\t\t\tli\n\t\t\t\t\ta(href=\"\") Contacto\n\t\t\t\tli\n\t\t\t\t\ta(href=\"\") Términos de Uso\n\t\t\t\tli\n\t\t\t\t\ta(href=\"\") Políticas de privacidad\n\t\t\tdiv.parrafo-footer\n\t\t\t\tp Copyright Guía Turística México © 2015. Todos los derechos reservados. Prohibida la reproducción parcial o total sin previa autorización expresa y por escrito de Directorios y Guías VB SA de CV. Génova 20-5, colonia Juárez, C.P. 06600, México D.F.\n\t\t\t\tspan Desarrollado por \n\t\t\t\t\ta(href=\"\") Meinen.mx\n\n\tscript(src=\"scripts/jquery.js\")\n\tscript(src=\"../scripts/jquery.cookie.js\")\n\tscript(src=\"scripts/jquery-changes.js\")\n\t\n\n\n\n\n\n\n\n\n\n");
}
}